spring:
  application:
    name: product-service
  config:
    activate:
      on-profile: localhost
  main:
    allow-bean-definition-overriding: true
info:
  component: Product Service

logging:
  level:
    root: INFO
    console: "%d{yyyy-MM-dd HH:mm:ss} %-5level %logger{36} - %msg%n"

server:
  port: 9788

---
spring:
  config:
    activate:
      on-profile: localhost
  cloud:
    config:
      url: http://localhost:8888
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    url: "jdbc:postgresql://localhost:5432/stock_management"
    username: postgres
    password: root
